#!/bin/bash
cd $FG_DEV
cd ..
trees=$(pwd)/trees
echo $trees
cd $trees
repo_url=$1
repo_git="$(basename $repo_url)"
repo_name="${repo_git%.*}"
echo $repo_name
if [[ ! "$2" == "" ]]; then
  mkdir -p $trees/$2
  cd $trees/$2
fi
git clone $repo_url
if [[ $? == 0 ]]; then
  echo "$repo_name cloned in $(pwd)"
else
  echo "ls $(pwd)"
  ls $(pwd)
fi
cd $FG_DEV
echo $FG_DEV