#!/bin/bash

cd ${FG_DEV}

std_options="$(<${SCRIPT_DIR}/std-options.txt)"
echo $std_options
tree=$1
if [[ "$tree" == "" ]]; then 
  tree="next"
elif [[ "${tree:0:1}" == "-" ]]; then
 tree="next"
else
shift
fi
if [[ -d trees/$tree ]];then 
  export FG_HOME="$PWD/trees/$tree/.fgfs"
  export FG_SCENERY="$PWD/$trees/scenery/"
  export FG_AIRCRAFT="$PWD/$trees/aircraft"  cd trees/$tree/install/flightgear/bin
  export FG_ROOT=$PWD/../fgdata
  export LD_LIBRARY_PATH='../../simgear/lib:../../openscenegraph/lib:../../openrti/lib:../../plib/lib'"${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"
  run_command="valgrind --leak-check=full -s $PWD/fgfs ${std_options} $@"
  echo "Running Flightgear with valgrind --leak-check=yes in ${PWD}"
  echo ${run_command}
  time ${run_command}
fi
exit
