#!/bin/bash
go(){
  trees=$FG_DEV/../trees
  cd $trees
  export FG_HOME="$PWD/$tree/.fgfs"
  export FG_ROOT="$PWD/$tree/install/flightgear/fgdata"
  export FG_SCENERY="$PWD/scenery/"
  export FG_AIRCRAFT="$PWD/aircraft"
  echo  "FG_HOME:          $FG_HOME"
  echo  "FG_ROOT:          $FG_ROOT"
  echo  "FG_SCENERY:       $FG_SCENERY"
  echo  "FG_AIRCRAFT:      $FG_AIRCRAFT"
  cd     $tree
  cd     flightgear
  echo  "FlightGear:       $(git branch -v)"
  cd    ../simgear
  echo  "Simgear:          $(git branch -v)"
  cd    $trees/$tree
  ls -lah compilation_log,txt
  $FG_DEV/utilities/last-update $tree
  run_command="$PWD/run_fgfs.sh ${std_options} $@"
  echo ""
  echo "Running Flightgear with run_fgfs.sh in ${PWD}"
  echo ""
  echo ${run_command}
  echo ""
  time ${run_command}
}
if [[ "${MY_CALLSIGN}" == "" ]]; then
   echo "Please define an environment variable for your callsign"
   echo "in your ~/.bashrc"
   echo "for Example:"
   echo "export MY_CALLSIGN=N0000B"
   echo "We'll proceed with N0000B for now...."
   export MY_CALLSIGN=N0000B
fi
std_options="$(cat ${FG_DEV}/core/std-options.txt \
  |sed s/\$\{IP_ADDRESS\}/$(hostname -I | cut -d ' ' -f1)/ \
  |sed s/\$\{MY_CALLSIGN\}/${MY_CALLSIGN}/)"

tree=$1 

if [[ "$tree" == "" ]]; then 
  tree="next"
elif [[ "${tree:0:1}" == "-" ]]; then
  tree="next"
else
shift
fi
if [[ -d trees/$tree ]];then
  cd trees/$tree
  go $@ $tree 2>&1 |tee run_log.txt
else
  echo "Cannot find trees/$tree"
fi
exit
