#!/bin/bash
go(){
  trees=$FG_DEV/../trees
  cd $trees
  export FG_HOME="$PWD/$tree/.fgfs"
  export FG_ROOT="$PWD/$tree/install/flightgear/fgdata"
  export FG_SCENERY="$PWD/scenery/"
  export FG_AIRCRAFT="$PWD/aircraft"
  echo  "FG_HOME:          $FG_HOME"
  echo  "FG_ROOT:          $FG_ROOT"
  echo  "FG_SCENERY:       $FG_SCENERY"
  echo  "FG_AIRCRAFT:      $FG_AIRCRAFT"
  cd     $tree
  cd     flightgear
  echo  "FlightGear:       $(git branch -v)"
  cd    ../simgear
  echo  "Simgear:          $(git branch -v)"
  cd    $trees/$tree
  run_command="$PWD/run_fgfs.sh ${std_options} $@"
  echo ""
  echo "Running Flightgear with run_fgfs.sh in ${PWD}"
  echo ""
  echo ${run_command}
  echo ""
  time ${run_command}
}

std_options="$(<${FG_DEV}/core/std-options.txt)"
tree=$1 

if [[ "$tree" == "" ]]; then 
  tree="next"
elif [[ "${tree:0:1}" == "-" ]]; then
  tree="next"
else
shift
fi
if [[ -d trees/$tree ]];then
  cd trees/$tree
  go $tree 2>&1 |tee run_log.txt
else
  echo "Cannot find trees/$tree"
fi
exit
