#!/bin/bash

cd ${FG_DEV}
cd ../trees
trees=$(pwd)

cd -
tree=$1
if [[ "$tree" == "" ]]; then 
  tree="next"
fi
if [[ "$tree" == "fgdev" ]]; then
  cd ${FG_DEV}
  code ${FG_DEV}/fgdev.code-workspace
else

  if [[ -e "$trees/$tree/install/simgear" ]]; then
    if [[ ! -e trees/$tree/$tree.code-workspace ]]; then
      cp ${FG_DEV}/templates/fg.code-workspace trees/$tree/$tree.code-workspace
    fi
  export INSTALL_DIR_OSG=$trees/$tree/install/openscenegraph
  export INSTALL_DIR_SIMGEAR=$trees/$tree/install/simgear
  export INSTALL_DIR_FLIGHTGEAR=$trees/$tree/install/flightgear
  d=$(realpath trees/$tree/install)
  export LD_LIBRARY_PATH=$d/simgear/lib:$d/openscenegraph/lib:$d/openrti/lib:$d/plib/lib${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}

  code trees/$tree/$tree.code-workspace
  else
  if [[ ! -e trees/$tree/$tree.code-workspace ]]; then
      cp ${FG_DEV}/templates/other.code-workspace trees/$tree/$tree.code-workspace
  fi
  cd $trees/$tree
  code $tree.code-workspace
  fi

fi
