#!/bin/bash

cd ${FG_DEV}

tree=$1
if [[ "$tree" == "" ]]; then 
  tree="next"
fi
if [[ ! -e trees/$tree/$tree.code-workspace ]]; then
  cp ${FG_DEV}/templates/next.code-workspace trees/$tree/$tree.code-workspace
fi
code trees/$tree/$tree.code-workspace
